let placesArray = [
  {
    name: "Asian Market",
    description: "Supermarket",
    address_1: "1221 Bakersfield Rd,",
    address_2: "Columbia, SC 29210",
    hours: "Mon-Sun 11am-6pm",
    status: "A little busy",
    phone: "(803) 772-9562",
    website: "https://asianmarketcola.business.site/",
    safety: "5/5",
    thumbnail: "./images/asianMarket.png",
  },
  // {
  //   name: "Devils Fork State Park",
  //   description: "Public park",
  //   address_1: "161 Holcombe Cir,",
  //   address_2: "Salem, SC 29676",
  //   hours: "Mon-Sun 7am-9pm",
  //   status: "Not busy",
  //   phone: "(864) 944-2639",
  //   website: "https://southcarolinaparks.com/devils-fork",
  //   safety: "3/5",
  //   thumbnail: "../images/devilsFork.jpg",
  // },
  // {
  //   name: "Costco",
  //   description: "Warehouse supermarket",
  //   address_1: "507 Piney Grove Rd,",
  //   address_2: "Columbia, SC 29210",
  //   hours: "Mon-Fri 10am-8:30pm, Sat 9:30am-6pm, Sun 10am-6pm",
  //   status: "Busier than usual",
  //   phone: "(803) 875-7130",
  //   website: "https://www.costco.com/warehouse-locations/columbia-sc-1232.html",
  //   safety: "2/5",
  //   thumbnail: "../images/Costco.png",
  // },
]